name = "velvet-experiments"
version = "0.1.0"
defaultTargets = ["Extensions"]

[[require]]
name = "Velvet"
git = "https://github.com/verse-lab/velvet"
rev = "9a61202"

[[lean_lib]]
name = "Extensions"

[[lean_lib]]
name = "llmgen"
globs = ["llmgen.+"]
