import Generated.CountVotesForCandidate
import Generated.ElectLeaderByMaxId
import Generated.FilterAliveNodes
import Generated.HasMajority
import Generated.NextNodeInRing
import Generated.ShouldAcceptTerm
